CREATE TABLE revmax_flight_arrival (
  id serial NOT NULL,
  type varchar(15),
  carrier_fs_code varchar(5),
  flight_number varchar(5),
  departure_airport_fs_code varchar(5),
  arrival_airport_fs_code varchar(5),
  stops int,
  departure_terminal varchar(5),
  arrival_terminal varchar(5),
  departure_time timestamp without time zone ,
  arrival_time timestamp without time zone ,
  flight_equipment_iata_code varchar(5),
  flight_equipment_data jsonb,
  flight_type text,
  flight_capacity int,
  service_type varchar(5),
  service_classes varchar(20)[],
  traffic_restrictions varchar(20)[],
  complete_response jsonb,
  created_at date,
  updated_at date,
  CONSTRAINT pk_revmax_flight_arrival PRIMARY KEY(id)
);
